name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : apt install dependency
      run: |
        sudo apt-get -y install valgrind --fix-missing
        udo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev --fix-missing
        
    - name: make valgrind
      run: make valgrind -C 03_Implementation

